---
title: "Lab 5"
author: "Rebecca. Sebastian"
date: "9/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Lab 5:Data wrangling and graphing COVID-19 reporting data (Part 2)

library(tidyverse)
library(readr)
library(lubridate)


Confirmed_State_3_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>% 
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 

Confirmed_State_3_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>% 
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter (Country_Region == "US") %>% 
  select(Province_State, Country_Region, Confirmed)


Confirmed_State_6_13 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>%
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 

Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>%
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 

setdiff(Confirmed_State_6_13$Province_State, Confirmed_State_9_13$Province_State)

Confirmed_State_9_13 <- Confirmed_State_9_13 %>% 
  filter(Province_State != "Recovered") 

Confirmed_State_6_13 <- Confirmed_State_6_13 %>% 
  filter(Province_State != "Recovered") 

Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
                                              Confirmed_State_9_13, by = c("Province_State")) %>% 
  rename(Confirmed_State_6_13 = "Confirmed.x", Confirmed_State_9_13 = "Confirmed.y" ) %>% 
  select(-Country_Region.x, -Country_Region.y) %>% 
view(Confirmed_State_6_13_9_13_joined)

## checking for NA's
which(is.na(Confirmed_State_6_13_9_13_joined))
  
## there are no NA's in the newly joined file

# coverting to a long dataset
Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
  pivot_longer(-c(Province_State),names_to = "Date", values_to = "Confirmed")

```


## 2 and 3
#plotting the data
```{r, fig.width = 5, fig.height= 10}
ggplot(data = Confirmed_State_6_13_9_13_joined_long, aes(Province_State, Confirmed, fill = Date)) +
  geom_bar(stat='identity')+
  labs(title = "Confirmed cases through time",
       x = "Province/State",
       y = "Confirmed") +
  theme_bw() +
  theme(legend.position = "bottom")

```

# working with time series data
```{r}

download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", 
              destfile = "data/time_series_covid19_confirmed_global.csv")

time_series_confirmed <- read_csv("data/time_series_covid19_confirmed_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

head(time_series_confirmed)

# Converting to a long dataset
time_series_confirmed_long <- time_series_confirmed %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Confirmed") 

# getting the deaths data
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
              destfile = "data/time_series_covid19_deaths_global.csv")

time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")

time_series_deaths_long <- time_series_deaths %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long),
               names_to = "Date", values_to = "Deaths") 

time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)

time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)

time_series_long_joined <- full_join(time_series_confirmed_long,
                                     time_series_deaths_long, by = c("Key")) %>% 
  select(-Key)

which(is.na(time_series_long_joined$Confirmed))
which(is.na(time_series_long_joined$Deaths))

time_series_long_joined$Date <- mdy(time_series_long_joined$Date)

# 4
time_series_long_joined %>% 
  group_by(Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  ggplot(aes(x = Date,  y = Deaths,))+ 
  geom_point()+
  geom_line()+
  ggtitle("COVID-19 Deaths Per Day Worldwide")

# 5

time_series_long_joined <- time_series_long_joined %>% 
  mutate(deaths_confirmed = Deaths/Confirmed) %>% 
  replace_na(list(deaths_confirmed = 0))

# 6
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths","deaths_confirmed"), sum) %>% 
  filter (Country_Region == "US") %>% 
  ggplot(aes(x = Date,  y = deaths_confirmed,))+ 
  geom_point()+
  geom_line()+
  ggtitle("US COVID-19 Deaths/Confirmed Per Day")

#7 Finding the 10 countries with most number of deaths all time
top_10 <- time_series_long_joined %>% 
  group_by(Country_Region) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>%
  arrange(desc(Deaths)) %>% 
  top_n(10)

# plotting the data
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil","United Kingdom", 
                                "Italy","Mexico", "India","France","Spain","Iran","Peru")) %>% 
  ggplot(aes(x = Date,  y = Deaths, color = Country_Region)) + 
  geom_point() +
  geom_line() +
  ggtitle("COVID-19 Deaths for 10 countries with the hightest death total")
  
```

```{r, fig.width = 5, fig.height= 10}
#8
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil","United Kingdom", 
                                "Italy","Mexico", "India","France","Spain","Iran","Peru")) %>% 
  ggplot(aes(x = Date,  y = Deaths)) + 
  geom_point() +
  geom_line() +
  ggtitle("COVID-19 Deaths for 10 countries with the hightest death total") +
  facet_wrap(~Country_Region, ncol=2, scales="free_y")
```

```{r}
#9 Getting US time series data
## for deaths 
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv", 
              destfile = "data/time_series_covid19_deaths_US.csv")

US_time_series_deaths <- read_csv("data/time_series_covid19_deaths_US.csv")

US_time_series_deaths_long <- US_time_series_deaths %>% 
  rename(Long = "Long_") %>% 
  select(-c(UID, iso2, iso3, code3, FIPS)) %>% 
  pivot_longer(-c(Admin2, Province_State, Country_Region, Lat, Long, Combined_Key, Population),
               names_to = "Date", values_to = "Deaths") 

## for confirmed 
download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", 
              destfile = "data/time_series_covid19_confirmed_US.csv")

US_time_series_confirmed <- read_csv("data/time_series_covid19_confirmed_US.csv")

US_time_series_confirmed_long <- US_time_series_confirmed %>% 
  rename(Long = "Long_") %>% 
  select(-c(UID, iso2, iso3, code3, FIPS)) %>% 
  pivot_longer(-c(Admin2, Province_State, Country_Region, Lat, Long, Combined_Key),
               names_to = "Date", values_to = "Confirmed") 

US_time_series_confirmed_long <- US_time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)

US_time_series_deaths_long <- US_time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)

US_time_series_long_joined <- full_join(US_time_series_confirmed_long,
                                     US_time_series_deaths_long, by = c("Key")) %>% 
  select(-Key)

## Checking for NAs
which(is.na(time_series_long_joined$Confirmed))
which(is.na(time_series_long_joined$Deaths))

head(US_time_series_long_joined)
US_time_series_long_joined$Date <- mdy(US_time_series_long_joined$Date)

```

```{r, fig.width = 5, fig.height= 10}
## plotting the data
US_time_series_long_joined %>% 
  group_by(Province_State,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  ggplot(aes(x = Date,  y = Confirmed))+ 
  geom_point()+
  geom_line()+
  ggtitle("US COVID-19 Confirmed time trend")+
  facet_wrap(~Province_State, ncol=5, scales="free_y")
```

```{r}
## 10
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region %in% c("US","Brazil","United Kingdom", 
                                "Italy","Mexico", "India","France","Spain","Iran","Peru")) %>% 
  ggplot(aes(x = Date,  y = Deaths)) + 
  geom_point() +
  geom_line() +
  ggtitle("COVID-19 Deaths for 10 countries with the hightest death total") +
  facet_wrap(~Country_Region, ncol=2, scales="free_y")+
  theme_classic()+
  theme(text = element_text(size = 11))

```

